### ISSUE TITLE
Animation looks squashed on Firefox

### ISSUE THREAD

**Issue by nt1m** [alyssaxuu/animockup#1]
This looks really promising, thanks for making this! :)

I just wanted to report a small issue I found on Firefox:
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/1795135/77240237-ef043500-6be3-11ea-9516-cca45e2128ae.png">

**Comment by alyssaxuu** [comment]
Hmm, odd, is this on load? Will try to replicate to pinpoint the issue. Also would be interesting to know whether it also happens when you upload your own footage. If I recall the initial screen is placed differently to the user-submitted ones so it could have something to do with that.

Going to try to fix this ASAP though!

**Comment by nt1m** [comment]
I cloned the repository locally and manually uploaded `video.mp4` from the repo as "Device screen", and it also displayed broken. 

Thanks for looking into this! Please let me know if I can help debug this in any other way :)

**Comment by alyssaxuu** [comment]
Just downloaded Firefox to test and indeed, the startup video is broken. I did try placing other footage and it went corner to corner though, so I feel it has to be related to how the first video is initialized. Hopefully I can have it fixed soon :)

**Comment by alyssaxuu** [comment]
Looking into it, it is so strange. I am worried it might have to do with how Firefox renders video - I've tried a multitude of tweaks and whenever it looked right on Firefox, it looked wrong in other browsers. Might need to research this further, it could have to do with the video not being fully loaded in Firefox before retrieving its dimensions too.

**Comment by alyssaxuu** [comment]
![image](https://user-images.githubusercontent.com/7581348/77241408-e9d8c300-6bae-11ea-8b0b-a19c8fbfa008.png)

This is super odd. Both browsers report the video being the same height and width (those are the numbers showing in the console of both browsers, the first is the width, the second is the height), but in Firefox, the height for some reason looks different. If I try "manually fixing it" by increasing the height, I can manage to make it look full height in Firefox, but then it looks way too long in Chrome.

I have to admit this is sort of driving me mad. What I know is that FabricJs will use width and height amounts simply for cropping the video (so no scaling), and then scaleX/scaleY for increasing and decreasing the width and height respectively. I thought maybe it could have to do with that, maybe with the source video being a different height (e.g. accounting for transparent pixels?), but when I check the original footage's dimensions (prior to the transformation), they also show as the same in either browser.

I'm out of ideas here, it could just be an issue with FabricJs, I'll need to keep researching.

**Comment by alyssaxuu** [comment]
Okay, I "fixed" the issue by using a browser hack to increase the height of the video in Firefox only. It's not pretty, and it still hasn't led me to the source of the problem, but at least it should work for now. Going to close it as it works, but I will still keep researching why it has this browser disparity.

**Comment by nt1m** [comment]
@alyssaxuu Thanks for quickly looking into it! 
The workaround seems to work for the intro, but if I upload that exact same video as "Device Screen", the video looks squashed again. 

I made a quick reduced testcase to try and debug this: [Archive.zip](https://github.com/alyssaxuu/animockup/files/4364640/Archive.zip)

I'll let you know if I find something.

**Comment by emilio** [comment]
Here's an actually reduced test-case @nt1m:

```html
<!doctype html>
<canvas width=500 height=500></canvas>
<br>
<video src="video.mp4" height="2436" width="1124" loop></video>
<script>
onload = function() {
  let video = document.querySelector("video");
  video.currentTime = 2.0;
  document.addEventListener("click", function f() {
    let ctx = document.querySelector("canvas").getContext("2d");
    ctx.transform(0.17793594306049823, 0, 0, 0.17793594306049823, 100, 216.72597864768684);
    ctx.drawImage(video, 0, 0, 1124, 2436, -562, -1218, 1124, 2436);
  });
}
</script>
```

I haven't dug which one is the right rendering though, I'd file a bug just in case.

**Comment by emilio** [comment]
I think this is a Chrome bug. If I extract one video frame with ffmpeg and use it as an `<img>` on the drawImage call, then Chrome renders like Firefox.

**Comment by emilio** [comment]
I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1063683. Safari agrees with the `<img>` rendering and doesn't support `<video>` as a drawImage argument.

**Comment by kintaro1981** [comment]
the problem on firefox is still there :-(
