### ISSUE TITLE
Verizon and Chrome flagging as malicious

### ISSUE THREAD

**Issue by megaroeny** [alyssaxuu/animockup#2]
Your site is getting flagged as a malicious website by Verizon FiOS, McAfee, and Chrome. Can you look into this so I can safely check it out? Thanks!

**Comment by alyssaxuu** [comment]
Hmmm that's not good. Disputing it immediately - it might have to do with the technique I am using to render videos & convert to GIF, which is all done client-side. Hopefully I manage to get it fixed...

**Comment by alyssaxuu** [comment]
Should be fixed now.
